# Generated by Django 4.2 on 2025-08-11 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('days', models.IntegerField()),
                ('budget', models.CharField(choices=[('budget', 'Budget-friendly'), ('mid-range', 'Mid-range'), ('luxury', 'Luxury')], default='mid-range', max_length=50)),
                ('travel_style', models.CharField(choices=[('adventure', 'Adventure'), ('cultural', 'Cultural'), ('relaxation', 'Relaxation'), ('family', 'Family-friendly'), ('business', 'Business')], default='cultural', max_length=50)),
                ('generated_itinerary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
